[workspace]
authors = ["TerenceLiu <terenceliu1012@gmail.com>"]
channels = ["conda-forge"]
name = "newsfeed"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
beautifulsoup4 = ">=4.14.3,<5"
fake-useragent = ">=2.2.0,<3"
nltk = ">=3.9.2,<4"
numpy = ">=2.4.0,<3"
pandas = ">=2.3.3,<3"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.5,<3"
lxml = ">=6.0.2,<7"
lxml-html-clean = ">=0.4.3,<0.5"
tenacity = ">=9.1.2,<10"
aiohttp = "*"
aiofiles = "*"
pyarrow = "*"
joblib = "*"
pytest = ">=9.0.2,<10"
newspaper4k = ">=0.9.4.1"